name:                h-json-schema-data
version:             0.0.0.1
github:              "isomarcte/h-json-schema-data"
license:             BSD3
author:              "David Strawn"
maintainer:          "isomarcte@gmail.com"
copyright:           "2019 David Strawn"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/isomarcte/j-json-schema-data#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers
- nonempty-containers
- text
- unordered-containers
- uri-bytestring

ghc-options:
  - -Wall
  - -Werror

data-files:
  - data/test/example/*.json

library:
  source-dirs: src

default-extensions:
  - DeriveGeneric
  - EmptyDataDecls
  - FlexibleContexts
  - GADTs
  - GeneralizedNewtypeDeriving
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - StandaloneDeriving
  - StrictData

tests:
  h-json-schema-data-test:
    main:                Spec.hs
    generated-other-modules:
    - Paths_h_json_schema_data
    other-modules:
    - Property.JsonGenerators
    - Property.JsonSchemaGenerators
    - Property.JsonSchemaProperties
    - Property.QuickCheckUtilities
    - Unit.ExampleSchemas
    - Unit.ParseExamples
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-orphans
    dependencies:
    - h-json-schema-data
    - QuickCheck
    - filepath
    - mtl
    - quickcheck-text
    - scientific
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - vector
